source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem 'boundary', path: '../../../boundary'

gemspec

group :development, :test do
  gem 'byebug'
  gem 'pry'
  gem 'rspec'
end
