name: Ruby
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
#        ruby-version: ${{ matrix.ruby }}
        ruby-version: 2.7
    - name: Run the default specs
      run: bundle exec rake
    - name: Run the specs of test application
      run: cd test_app && bundle exec rake
